<a href="https://colab.research.google.com/github/ErmachenkoBoris/three-dimensional-computer-vision/blob/master/homeWork28-10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Ермаченко Борис, домашнее задание от 28.10.2020

## №1

In [ ]:

!pip install opencv-python

In [ ]:
import numpy as np
import cv2


In [ ]:
from IPython.display import Image 

Чтобы найти ближайшую ортогональную матрицу, используется сингулярное разложение.
Применим формулу X = UV^T

In [ ]:

A = [[0.5,        2.16506351, 0.4330127],
     [-0.8660254, 1.25,       0.25     ],
     [0,          0.5,        2.5      ]]
     


In [ ]:
A = np.array(A)

In [ ]:
D, U, Vt = cv2.SVDecomp(A)

In [ ]:
X = np.matmul(U, Vt)


In [ ]:
print(X)

[[ 5.00000000e-01  8.66025404e-01 -3.87999696e-10]
 [-8.66025404e-01  5.00000000e-01  1.65509423e-11]
 [ 2.08333333e-10  3.27741947e-10  1.00000000e+00]]


In [ ]:
display(Image(url='https://i.stack.imgur.com/HRe73.jpg', 
              width = 200)
       ) 
# матрицы поворота в трехмерном пространстве

Таким образом, матрица похожа на матрицу поворота вокруг оси Z

In [ ]:

np.rad2deg(np.arcsin(-0.866025404))

-60.00000002470152

на 60 градусов

## №2

In [ ]:
def createMatrix(n):
    arr = [[1/((i+1)+(j+1)-1) for j in range(n)] for i in range(n)]
    A = np.array(arr)
    return A
    # нумерация с 1, чтобы избежать деление на ноль 

In [ ]:
A = createMatrix(3)

In [ ]:
print(A)

[[1.         0.5        0.33333333]
 [0.5        0.33333333 0.25      ]
 [0.33333333 0.25       0.2       ]]


Будем искать обратную матрицу по формуле : X = VD^(-1)U^t, где D^(-1) - псевдообратная к матрице D

In [ ]:
def findInvMatrix(A):
  D, U, Vt = cv2.SVDecomp(A)
  V = Vt.transpose()
  Ut = U.transpose()
  Dx = np.diag(1 / D.flatten())
  #tmp = np.matmul(V, Dx)
  #X = np.matmul(tmp, Ut)
  X = V.dot(Dx).dot(Ut)
  return X

In [ ]:
matrix1 = findInvMatrix(A)
print(matrix1)
# Обратная матрица для N = 3

[[   9.  -36.   30.]
 [ -36.  192. -180.]
 [  30. -180.  180.]]


In [ ]:
B = createMatrix(10)
print(B)
matrix2 = findInvMatrix(B)
print("Обратная матрица для N = 10")
print(matrix2)
# Обратная матрица для N = 3

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1       ]
 [0.5        0.33333333 0.25       0.2        0.16666667 0.14285714
  0.125      0.11111111 0.1        0.09090909]
 [0.33333333 0.25       0.2        0.16666667 0.14285714 0.125
  0.11111111 0.1        0.09090909 0.08333333]
 [0.25       0.2        0.16666667 0.14285714 0.125      0.11111111
  0.1        0.09090909 0.08333333 0.07692308]
 [0.2        0.16666667 0.14285714 0.125      0.11111111 0.1
  0.09090909 0.08333333 0.07692308 0.07142857]
 [0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
  0.08333333 0.07692308 0.07142857 0.06666667]
 [0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308 0.07142857 0.06666667 0.0625    ]
 [0.125      0.11111111 0.1        0.09090909 0.08333333 0.07692308
  0.07142857 0.06666667 0.0625     0.05882353]
 [0.11111111 0.1        0.09090909 0.08333333 0.07692308 0.07142857
  0.06666667 0.0625     

## №4

Пусть имеем две прямые ax+by+c= 0, cx+dy+e=0.
Будем генерировать a,b,c,d,e случайным образом

In [ ]:


l1 = np.random.rand(3)
l2 = np.random.rand(3)

In [ ]:
print(l1, l2)

[0.30323216 0.82876493 0.13844457] [0.56466907 0.9989435  0.92680401]


 Чтобы найти точку пересечения двух линий l1,l2, нужно найти их векторное произведение

In [ ]:
p = np.cross(l1, l2)
print(p)

[ 0.62980436 -0.20286142 -0.16506613]


Найдем координаты при проекции на плоскость:


In [ ]:
ph=[p[0]/p[2],p[1]/p[2], 1]
print(ph)

[-3.815466913245131, 1.2289705697340803, 1]


## №3


AX=0 .Можно трактовать X как правый сингулярный вектор, тогда соответсвующее сингулярное число должно равняться нулю

In [ ]:
arr1 = [[((i)+(j)-1)/1 for j in range(4)] for i in range(4)]
C = np.array(arr1)
print(C)

[[-1.  0.  1.  2.]
 [ 0.  1.  2.  3.]
 [ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]]


In [ ]:
 D1, U1, Vt1 = cv2.SVDecomp(C)

In [ ]:
print(D1)

[[1.00000000e+01]
 [2.00000000e+00]
 [2.57348462e-16]
 [9.25320984e-17]]


 Заметим, что числа, стоящие в 3 и 4 строке очень малы, считаем их нулями

Произведем проверку:

In [ ]:
V1 = Vt1.transpose()


print(np.matmul(C, V1[:,2]))
print(np.matmul(C, V1[:,3]))

[ 1.11022302e-16 -3.81639165e-17 -2.22044605e-16 -4.44089210e-16]
[0.00000000e+00 2.22044605e-16 0.00000000e+00 0.00000000e+00]


Получили очень маленькие значения. Делаем вывод, что решением будут являться следующие вектора:

In [ ]:
print( V1[:,2])
print( V1[:,3])

[ 0.5349343  -0.80094882 -0.00290524  0.26891977]
[ 0.11766605  0.24182842 -0.83665498  0.47716052]
